import pandas as pd
import os

# Paths for reading and saving
# Save the plots
plot_path = r'XXXXX'
# The word vectors
word_vector_path = r'XXXXX'
# Desktop
desktop = r'XXXXX'
# Tweet 2016 Path
tweet_2016 = r'XXXXX'
# Tweet 2017 Path
tweet_2017 = r'XXXXX'
# Path used to save the Chinese tweets and English tweets in each transit neighborhood based on the tweet geoinformation
station_related_path_zh_en = r'XXXXX'
# Path to generate the data for human review
prepare_for_the_review_path = r'XXXXX'
# Save the human reviewed dataset
review_path = r'XXXXX'
# Save the result from human review
human_review_result_path = r'XXXXX'
# Save the topic modelling result
topic_modelling_path = r'XXXXX'
before_and_after_topic_modelling_compare = r'XXXXX'
# Save plots generated by LDA
lda_plot_path = r'XXXXX'
# Save the result derived from ArcGis
arcgis_path = r'XXXXX'
# Save the tweet representations
tweet_representation_path = r'XXXXX'
transit_non_transit_comparison_before_after = \
    r'XXXXX'
transit_non_transit_comparison_cross_sectional = \
    r'XXXXX'


# The location of the stations
# The 'station_location.csv' file contains the name of stations as well as their corresponding geoinformation, which could be found
# in the Datasets folder
location_df = pd.read_csv(os.path.join(tweet_2017, 'station_location.csv'))
location_stations = {}
for _, row in location_df.iterrows():
    location_stations[row['Name']] = (row['lat'], row['lon'])
